name: Feature Request
description: Request a new feature or enhancement
title: "[Feature Request]: "
labels: [ "enhancement" ]
body:
  - type: dropdown
    id: affected_card
    attributes:
      label: Affected Card Type
      description: Which card type is affected by your suggestion?
      options:
        - public-transport-connections-card
        - public-transport-connection-card
        - public-transport-departures-card
    validations:
      required: false
  - type: input
    id: home_assistant_version
    attributes:
      label: Home Assistant Version
      description: Does your feature request relate to a specific version or a feature just released in a specific version?
    validations:
      required: false
  - type: input
    id: sensor_integration
    attributes:
      label: Public Transport Sensor Integration
      description: Does your request relate to a specific public transport integration (e.g. ha-bahnvorhersage, hacs-hafas)?
    validations:
      required: false
  - type: textarea
    id: feature_description
    attributes:
      label: Description of the feature
      description: Please describe the feature you would like to see implemented. Include any relevant details.
    validations:
      required: true
